### ISSUE TITLE
add "problem" information into hdf5 dump file header

### ISSUE THREAD

**Issue by gnwong** [AFD-Illinois/iharm3d#11]
As previously discussed, I propose adding a customizable ```/header/problem``` group into the structure of every hdf5 dump file produced by iharm (and its derivatives). I suggest implementing this change in the following manner:

1) Require the definition of a macro in problem.c (could be in parameters.h as well, but keeping it in problem.c makes it easier to reconcile the structural differences between iharm3d and ebhlight) named something like ```PROBLEM_ID```, which should resolve to a unique string which can be used to identify the exact "problem" type. The obvious choice for this name would just be the name of the problem itself, since there can never be collisions here. This macro would be written to ```/header/problem/id``` in every dump file and thus would become a part of the standard.

2) Each problem.c file must also implement a function like ```void set_problem_details()``` which would fill out the rest of the ```/header/problem``` group with problem-specific details. Because this is defined on a per-problem basis, it makes it easier for new developers to add new problems without much thought. This function would be called during the ```io.c:dump(...)``` function call after ```hdf5_create(fname);``` has been called. 

Thoughts?

**Comment by vedantdhruv96** [comment]
iharm3d now stores problem-specific data

https://github.com/AFD-Illinois/iharm3d/pull/18
https://github.com/AFD-Illinois/iharm3d/pull/20
