### ISSUE TITLE
iharm3d does not record all details of initial problem in header

### ISSUE THREAD

**Issue by bprather** [AFD-Illinois/iharm3d#15]
Neither the inner and max radius of the initial Fishbone-Moncrief torus R_{in,max}, nor the initial magnetic field ratio beta_max, are recorded in dump files.  Since these are of course crucial parameters to reproducing the run, they should be included in the output header.

**Comment by gnwong** [comment]
https://github.com/AFD-Illinois/iharm3d/issues/11
